name: Python CI Workflow
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Праздников Максим Кириллович"
      GROUP_NUMBER: "М3111"
    steps:
    - uses: actions/checkout@v4  # Добавляем этот шаг первым!
      
    - name: Debug directory
      run: |
        pwd
        ls -la
        
    - name: Print user details
      run: |
        echo "ФИО: ${{ env.FULL_NAME }}"
        echo "Номер группы: ${{ env.GROUP_NUMBER }}"
        echo "GitHub username: ${{ github.actor }}"
        
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        
    - name: Install dependencies
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
        
    - name: Check code style
      run: |
        pip install flake8
        flake8 . --max-line-length=80
        
    - name: Format code with black
      run: |
        pip install black
        black .
